theme: cube

# background display for mobile, not for pc
header:
  background: http://josephliu.xyz/download/website/background/prekracnoe-daleko-2400x1277.jpg
  # both pc and mobile required title(make it the same as your hexo site _config.yml's title)
  title: Joseph Liu の 窝


# background display for pc
# you can use url or path relative
# `background: background.png` refers to the path "source/images/background.png"
background: http://josephliu.xyz/download/website/background/prekracnoe-daleko-2400x1277.jpg


# the background image width and height (you can see your image file to get them)
width: 2400
height: 1277


# this variable is used to locate your background
# for example, if you want to locate display your background from top
# you just need to type it: position: 0
position: 400


# this variable is used to make the background header being fuzzy
# if your do not need the filter blur on the top, make it empty, it means that: `blur: `
blur: 5


# yeah, it is just to make your avatar rounded(true) or not(false)
avatar: true

menu:
  # index
  - title: 首页
    icon: home
    url: /
  # archives
  - title: 归档
    icon: archive
    url: archives
  # categories
  - title: 分类
    icon: categories
    url: categories
  # tags
  - title: 标签
    icon: tags
    url: tags
  # about-me
  - title: 关于我
    icon: about
    url: about-me

sidebar:
  links:
    - title: GitHub
      url: https://github.com/ToKiNoBug
      # icon can be url or path
      icon: https://webdav.josephliu.xyz/download/website/icon/github.png
    - title: Bilibili
      url: https://space.bilibili.com/351429231
      icon: https://webdav.josephliu.xyz/download/website/icon/bilibili.png
  friend_links:
    - title: Cubik65536
      url: https://cubik65536.top/
      icon: https://josephliu.xyz/download/website/icon/cubik65536.jpg

# only path, refer to source/images
friend_links: friend_links.jpg

widgets:
- search
- author
- music
- recent_posts
- categories
- tagcloud
- links
- friend_links

# when you want to use the search, firstly make the `search: true`,
# then you should install hexo-generator-json-content
# run `npm install hexo-generator-json-content -save` (in your hexo directory)
search: true

# supported by DIYgod awesome project APlayer, you can find more on https://github.com/MoePlayer/APlayer
# and you can see the doc on https://aplayer.js.org/docs/#/

# mode can be `random`, `single`, `circulation`(loop), `order`(no loop)
# if you have the lrc file, make the `showlrc` true, else make it false
music_setting:
  auto: false
  mode: circulation
  narrow: false
  mutex: true
  showlrc: true
  theme:
  preload: auto
  maxHeight: 513px

# if you use path, make sure your hexo _config.yml has set the correcting url
# url: http://www.yoururl.com/path/to/.mp3 or .lrc or ...
# you'd better place your music and image, lrc to another site, and use url instead of path
# if you don't want to use this widget, just make that `music: `
music:
  - title: 最美好的前程 Прекрасное далеко
    author: 尤·恩津（词），叶·克瑞拉托夫（曲），薛范（译配）
    source: https://josephliu.xyz/download/website/mp3/prekrasnoe_daleko.mp3
    lrc: https://josephliu.xyz/download/website/lrc/prekrasnoe_daleko.lrc
    image: https://josephliu.xyz/download/website/icon/black_october.jpg

  - title: 伊里奇 Ильич
    author: АнимациЯ
    source: https://josephliu.xyz/download/website/mp3/ilichi.mp3
    #lrc:
    image: https://josephliu.xyz/download/website/icon/ilichi.jpg

  - title: 战斗仍将继续 И вновь продолжается бой
    author: 尼·多布龙拉沃夫（词），阿·巴赫慕托娃（曲）
    source: https://josephliu.xyz/download/website/mp3/i_vnov_prodolzhaetsya_boii.mp3
    #lrc:
    image: https://josephliu.xyz/download/website/icon/sablin.jpg

  - title: 两世之间 Between the Two Worlds
    author: Project Mili
    source: https://josephliu.xyz/download/website/mp3/between_two_worlds.mp3
    #lrc:
    image: https://josephliu.xyz/download/website/icon/between_the_two_worlds.jpg


    #https://josephliu.xyz/download/website/icon/gagalin.jpg

    #

# before using the comment
# make use you know how to set the params
comment:
  # your disqus_shortname
  disqus:
  changyan:
    appid:
    conf:
  youyan:
  # gitment: https://github.com/imsun/gitment
  # make sure you know how to set it
  gitment:
    owner:
    repo:
    oauth:
      client_id:
      client_secret:

# some setting about comment module
comment_setting:
  changyan:
    hide_notice: true

analytics:
  baidu:
  google: